// Package adapter defines the central ProviderAdapter interface that every
// upstream provider integration must implement.
//
// This file is the load-bearing contract for modelhub. Per ADR-003, the
// interface MUST stay provider-agnostic — no fal-specific fields, no
// OpenAI-style tool-calling parameters, no Replicate cog references.
// If a code reviewer can identify the upstream provider from anything
// in this file, the abstraction has leaked.
package adapter

import (
	"context"
	"errors"
	"time"
)

// ─────────────────────────────────────────────────────────────────────────
// Identity types
// ─────────────────────────────────────────────────────────────────────────

// ProviderKey identifies an upstream provider in the registry.
// Examples: "bfl", "google-ai", "openai".
type ProviderKey string

// ModelKey identifies a specific model variant exposed to users via /v1/models.
// Examples: "flux-pro-1.1", "veo-3.0-pro", "gpt-image-1-edit".
// The format is opaque to the registry — manifests own the model identity.
type ModelKey string

// IdempotencyKey is a sha256-hex hash of (account_id, model, canonical_params, time_bucket).
// Generated by the caller (task layer); the adapter forwards it to upstream when supported.
// Bucket size is 60s per S5 ADR — see internal/task for canonicalization.
type IdempotencyKey string

// UpstreamRef is an opaque reference to a task on the upstream provider's side.
// The adapter is responsible for understanding its format. We persist it on the
// task row to support polling, cancellation, and webhook correlation.
type UpstreamRef string

// CostUSD is denominated in MICRO-DOLLARS (USD * 1_000_000) to avoid float pitfalls
// in wallet arithmetic. $0.04 = 40_000.
type CostUSD int64

// ─────────────────────────────────────────────────────────────────────────
// Domain enums (kept here to avoid import cycles with task/catalog packages)
// ─────────────────────────────────────────────────────────────────────────

// Modality describes the OUTPUT type a model produces. Note this is the
// output shape, not the input — image-edit takes an image input but produces
// an image output, so it lives in ModalityEdit only because its REQUEST shape
// differs (multipart upload pattern).
type Modality string

const (
	ModalityImage Modality = "image"
	ModalityVideo Modality = "video"
	ModalityAudio Modality = "audio"
	ModalityEdit  Modality = "edit" // image-in → image-out
	ModalityLLM   Modality = "llm"
)

// TaskKind describes the dispatch pattern for invoking a model.
//
//   - Sync       Submit blocks until result; UpstreamRef may be empty.
//   - Async      Submit returns UpstreamRef; caller polls (or receives webhook).
//   - Streaming  SSE/WebSocket; LLM-only for Sprint 1.
type TaskKind string

const (
	TaskKindSync      TaskKind = "sync"
	TaskKindAsync     TaskKind = "async"
	TaskKindStreaming TaskKind = "streaming"
)

// ─────────────────────────────────────────────────────────────────────────
// Request / response shapes
// ─────────────────────────────────────────────────────────────────────────

// Params is the validated, normalized input for a model invocation.
// The shape is per-model and validated against ModelManifest.InputSchema
// BEFORE Submit is called. Adapters MUST NOT do schema validation themselves —
// trust the caller. Adapters MAY translate from this canonical form into
// provider-specific shapes inside Submit.
type Params map[string]any

// SubmitResult is what an adapter returns from Submit().
type SubmitResult struct {
	// UpstreamRef is set for async; ignored for sync (use Inline instead).
	UpstreamRef UpstreamRef

	// Inline is set for sync results (TaskKindSync). When set, the caller
	// can skip polling entirely and proceed to NormalizeResult/Settle.
	Inline *NormalizedResult

	// AcceptedAt is when the upstream confirmed acceptance (200/202 returned).
	// Used to anchor SLA timeouts. State must NOT advance to Submitted before this.
	AcceptedAt time.Time
}

// PollResult is what an adapter returns from Poll().
type PollResult struct {
	Status PollStatus

	// Result is set when Status == StatusSucceeded. NormalizedResult.Outputs[*].URL
	// at this stage is the UPSTREAM URL, not our CDN URL — S9.5 asset worker
	// will rewrite it before any user-facing exposure.
	Result *NormalizedResult

	// Error is set when Status == StatusFailed.
	Error *PollError
}

// PollStatus is the adapter-level view of upstream task state.
// Distinct from internal/task.TaskState (which has more states for our internal
// FSM like Held, Settled, AssetLost). Mapping happens in the worker layer.
type PollStatus string

const (
	PollPending   PollStatus = "pending"
	PollRunning   PollStatus = "running"
	PollSucceeded PollStatus = "succeeded"
	PollFailed    PollStatus = "failed"
)

// PollError categorizes upstream failures so the caller can decide refund policy
// (full refund? partial? no refund because it was content policy?).
type PollError struct {
	Class   ErrorClass
	Message string // Human-readable; safe to surface to user after sanitization.
	Raw     []byte // Original upstream error body — for logs only, NEVER to user.
}

// ErrorClass is the canonical taxonomy for upstream failures.
type ErrorClass string

const (
	ErrClassAuth          ErrorClass = "auth"           // 401 — admin issue, user gets full refund
	ErrClassPayment       ErrorClass = "payment"        // 402 — modelhub out of upstream credit, full refund
	ErrClassRateLimit     ErrorClass = "rate_limit"     // 429 — back off, retry
	ErrClassContentPolicy ErrorClass = "content_policy" // upstream NSFW/policy reject — partial refund (compute portion)
	ErrClassUpstream      ErrorClass = "upstream"       // 5xx — full refund
	ErrClassNotFound      ErrorClass = "not_found"      // upstream ref expired/cleaned (e.g., BFL ~10min retention)
	ErrClassTimeout       ErrorClass = "timeout"        // exceeded our SLA — full refund
	ErrClassUnknown       ErrorClass = "unknown"        // Catch-all; alert ops
)

// NormalizedResult is the unified output shape across all providers/modalities.
// Adapters MUST map upstream-specific response shapes into this struct in
// NormalizeResult(). This is the layer that absorbs upstream API drift.
type NormalizedResult struct {
	Modality Modality
	Outputs  []Output       // Most models return 1; some return N (e.g., Flux num_images=4)
	Metadata map[string]any // Optional: seed used, model version actually run, upstream timing
}

// Output is a single result element. After S9.5 hosts it, URL is our CDN URL.
type Output struct {
	Type     OutputType
	URL      string // CDN URL post-S9.5; never an upstream URL exposed to user (per ADR-019)
	MimeType string
	Bytes    int64
}

// OutputType is the discriminator for the polymorphic NormalizedResult.Outputs.
type OutputType string

const (
	OutputImageURL OutputType = "image_url"
	OutputVideoURL OutputType = "video_url"
	OutputAudioURL OutputType = "audio_url"
	OutputText     OutputType = "text"
	OutputBase64   OutputType = "base64" // Some providers return inline base64; S9.5 still uploads to our CDN
)

// ProviderCaps describes which optional features an adapter supports.
// Used by the worker layer to decide whether to wire webhooks vs poll-only,
// surface Cancel buttons, etc.
type ProviderCaps struct {
	SupportsWebhook   bool
	SupportsCancel    bool
	SupportsStreaming bool

	// MaxConcurrent is a hint for our scheduler; 0 means no hint.
	// Used to avoid clobbering upstream rate limits.
	MaxConcurrent int
}

// ─────────────────────────────────────────────────────────────────────────
// The interface
// ─────────────────────────────────────────────────────────────────────────

// ProviderAdapter is the central abstraction. ONE implementation per upstream provider.
//
// Per ADR-003, this interface MUST stay provider-agnostic. Reviewer guard:
// if you can identify which upstream provider an adapter targets just by
// reading the interface signature, the interface has leaked.
//
// Implementations live in subpackages: internal/adapter/bfl, internal/adapter/googleai,
// internal/adapter/openai, etc. Each implementation registers itself with the registry
// in its package init() — but the registry itself ships in S2.5, not here.
type ProviderAdapter interface {
	// Key returns the registry key for this adapter. Stable for the lifetime of the process.
	Key() ProviderKey

	// Submit forwards a generation request to the upstream provider.
	// params is pre-validated against ModelManifest.InputSchema; the adapter
	// translates from this canonical form into provider-specific request shape.
	// idempotencyKey MUST be attached to the upstream request when the upstream
	// supports it (most do; X-Idempotency-Key is a common header).
	Submit(ctx context.Context, model ModelKey, params Params, idempotencyKey IdempotencyKey) (SubmitResult, error)

	// Poll fetches current state of a previously-submitted async task.
	// Callers MUST use exponential backoff with jitter; the adapter MUST NOT
	// add its own internal sleep loop (the worker schedules calls).
	Poll(ctx context.Context, ref UpstreamRef) (PollResult, error)

	// Cancel attempts to cancel an in-flight task.
	// Returns ErrUnsupported when Capabilities().SupportsCancel == false.
	Cancel(ctx context.Context, ref UpstreamRef) error

	// EstimateCost predicts the cost of a Submit call BEFORE it's made.
	// The wallet uses this for Hold sizing. Returned value MAY exceed actual cost;
	// Settle later reconciles using the actual upstream-reported cost (when available)
	// or this estimate (when not). Implementations should err on the side of
	// over-estimation to avoid over-Hold debits at the cost of slightly larger refunds.
	EstimateCost(model ModelKey, params Params) (CostUSD, error)

	// Capabilities returns the adapter's static feature flags.
	// MUST NOT vary between calls (no dynamic feature negotiation).
	Capabilities() ProviderCaps
}

// ─────────────────────────────────────────────────────────────────────────
// Sentinel errors
// ─────────────────────────────────────────────────────────────────────────

// ErrUnsupported is returned by Cancel (and future optional methods) when
// the adapter does not implement the operation. Callers MUST handle this
// distinctly from genuine errors.
var ErrUnsupported = errors.New("adapter: operation not supported")

// ErrNotConfigured is returned by any method when the adapter lacks required
// configuration (e.g., API key missing). Distinct from ErrClassAuth (which is
// a runtime auth rejection by upstream).
var ErrNotConfigured = errors.New("adapter: not configured")

// ErrInvalidParams is returned by Submit if the params fail provider-specific
// validation that couldn't be expressed in ModelManifest.InputSchema. This is
// a 400-class error, not a runtime failure; surfaced to user with sanitized message.
var ErrInvalidParams = errors.New("adapter: invalid params")
